export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY';
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL';

export const FETCH_COMMENT_BY_POST_ID = 'FETCH_COMMENT_BY_POST_ID';
