export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY';
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL';
export const POST_MODAL_STATE = 'POST_MODAL_STATE';
export const CREATE_POST = 'CREATE_POST';
export const EDIT_POST = 'EDIT_POST';
export const VOTE_POST = 'VOTE_POST';
export const DELETE_POST = 'DELETE_POST';

export const FETCH_COMMENT_BY_POST_ID = 'FETCH_COMMENT_BY_POST_ID';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const COMMENT_MODAL_STATE = 'COMMENT_MODAL_STATE';
export const VOTE_COMMENT = 'VOTE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';

export const ORDER_BY = 'ORDER_BY';
export const CHANGE_TYPE_OF_FILTER = 'CHANGE_TYPE_OF_FILTER';
