export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY';
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL';
export const POST_MODAL_STATE = 'POST_MODAL_STATE';

export const FETCH_COMMENT_BY_POST_ID = 'FETCH_COMMENT_BY_POST_ID';

export const ORDER_BY = 'ORDER_BY';
export const CHANGE_TYPE_OF_FILTER = 'CHANGE_TYPE_OF_FILTER';
